apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
  template:
    metadata:
      labels:
        app: productpage
    spec:
      containers:
      - name: productpage
        image: istio/examples-bookinfo-productpage-v1:1.16.0
        ports:
        - containerPort: 9080

