apiVersion: v1
kind: Service
metadata:
  name: productpage
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: productpage
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080

