name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trivy-scan:
    name: Trivy Installation & Scan
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Scan Docker image (optional)
        run: |
          docker build -t my-app:latest .
          trivy image my-app:latest

