name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:   # optional, allows manual trigger

jobs:
  build:
    runs-on: self-hosted   # <- THIS sends the job to your runner
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Print Hello
        run: echo "Hello from self-hosted runner!"

