name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:   # allows manual trigger

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]  # matches your self-hosted runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Hello
        run: echo "Hello from self-hosted runner!"

      - name: List current directory
        run: ls -la

