name: Test Self-Hosted Runner

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Print runner info
        run: |
          echo "Running on self-hosted runner"
          uname -a
