name: Runner Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - run: echo "✅ Self-hosted runner is working!"
      - run: uname -a
      - run: docker --version

